Formulario/Models/ViewModels/CrudViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Formulario.Models.ViewModels
{
    public class CrudViewModel
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; }
        [Required]
        [Display(Name = "Apellido")]
        public string Apellido { get; set; }
        [Required]
        [Display(Name = "Correo")]
        public string Correo { get; set; }
        [Required]
        [Display(Name = "Telefono")]
        public string Telefono { get; set; }
        [Required]
        [Display(Name = "Pais")]
        public string Pais { get; set; }
    }
}

Formulario/Models/ViewModels/ListCrudViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Formulario.Models.ViewModels
{
    public class ListCrudViewModel
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public string Pais { get; set; }
    }
}

Formulario/Controllers/CrudController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Formulario.Controllers;
using Formulario.Models;
using Formulario.Models.ViewModels;

namespace Formulario.Controllers
{
    public class CrudController : Controller
    {
        // GET: Crud
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult CreateUser(CrudViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using(FormEntities1 db = new FormEntities1())
                    {
                        var oCrud = new TB_Form();
                        oCrud.nombre = model.Nombre;
                        oCrud.apellido = model.Apellido;
                        oCrud.correo = model.Correo;
                        oCrud.pais = model.Pais;
                        oCrud.telefono = model.Telefono;

                        db.TB_Form.Add(oCrud);
                        db.SaveChanges();
                    }
                }
                return RedirectToAction("Dashboard");
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
            
        }

        public ActionResult Dashboard()
        {
            List<ListCrudViewModel> lst;
            using (FormEntities1 db = new FormEntities1())
            {
                lst = (from d in db.TB_Form
                       select new ListCrudViewModel
                       {
                           Id = d.id,
                           Nombre = d.nombre,
                           Apellido = d.apellido,
                           Correo = d.correo,
                           Telefono = d.telefono,
                           Pais = d.pais
                           
                       }).ToList();
            }
                return View(lst);
        }

        public ActionResult Delete(int id)
        {
            FormEntities1 db = new FormEntities1();
            TB_Form eliminar = db.TB_Form.Where(d => d.id == id).First();

            db.TB_Form.Remove(eliminar);
            db.SaveChanges();
            return RedirectToAction("Dashboard");
        }

        public ActionResult Update()
        {
            return View();
        }
    }
}

Formulario/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Formulario.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult SaveData()
        {
            

            return RedirectToAction("Index");
        }
    }
}

Formulario/Views/Crud/Create.cshtml
@model Formulario.Models.ViewModels.ListCrudViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div class="page-wrapper bg-gra-01 p-t-30 p-b-100 font-poppins">
        <div class="wrapper wrapper--w780">
            <div class="card card-3">
                <div class="card-heading"></div>
                <div class="card-body">
                    <h2 class="title">Información</h2>
                    @using (Html.BeginForm("CreateUser","Crud",FormMethod.Post))
                    {
                        <div class="input-group">
                            @Html.TextBoxFor(d => d.Nombre ,"", new { @class = "input--style-3" , @placeholder = "Nombre" , @type="text"})
                            @*<input class="input--style-3" type="text" placeholder="Nombre" name="name">*@
                        </div>
                        <div class="input-group">
                            @Html.TextBoxFor(d => d.Apellido, "", new { @class = "input--style-3", @placeholder = "Apellido", @type = "text" })
                            @*<input class="input--style-3 js-datepicker" type="text" placeholder="Apellido" name="lastName">*@
                            <i class="zmdi zmdi-calendar-note input-icon js-btn-calendar"></i>
                        </div>
                        <div class="input-group">
                            @Html.TextBoxFor(d => d.Correo, "", new { @class = "input--style-3", @placeholder = "Email", @type = "email" })
                            @*<input class="input--style-3 js-datepicker" type="email" placeholder="Correo" name="email">*@
                            <i class="zmdi zmdi-calendar-note input-icon js-btn-calendar"></i>
                        </div>
                        <div class="input-group">
                            @Html.TextBoxFor(d => d.Telefono, "", new { @class = "input--style-3", @placeholder = "Teléfono", @type = "text" })
                            @*<input class="input--style-3" type="text" placeholder="telefono" name="Telefono">*@
                        </div>
                        <div class="input-group">
                            @Html.TextBoxFor(d => d.Pais, "", new { @class = "input--style-3", @placeholder = "País", @type = "text" })
                            @*<input class="input--style-3" type="text" placeholder="país" name="Pais">*@
                        </div>
                        <div class="p-t-10">
                            <button class="btn btn--pill btn--green" type="submit">Enviar</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>

Formulario/Views/Crud/Dashboard.cshtml
@model List<Formulario.Models.ViewModels.ListCrudViewModel>
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div class="page-wrapper bg-gra-01 p-t-100 p-b-100 font-poppins">
        
        <div class="wrapper wrapper--w780">
            <a href="@Url.Action("Create","Crud")" class="btn btn--pill btn-primary ">Create</a>
            <div class="card card-3">

                <div class="card-body">
                    <table class="table table-dark" style="color:white;">
                        <thead>
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Nombre</th>
                                <th scope="col">Apellido</th>
                                <th scope="col">Correo</th>
                                <th scope="col">Telefono</th>
                                <th scope="col">Pais</th>
                            </tr>
                            </thead>
                        <tbody>
                            @foreach (var userr in Model)
                            {
                            <tr>
                                <th scope="row">@userr.Id</th>
                                <td>@userr.Nombre</td>
                                <td>@userr.Apellido</td>
                                <td>@userr.Correo</td>
                                <td>@userr.Telefono</td>
                                <td>@userr.Pais</td>
                                <td>@Html.ActionLink("Deletee", "Delete", new { id = userr.Id }, new { @class = "btn btn--pill btn-danger" })</td>
                                @*<td><a href="@Url.Action("Delete")" class="btn btn--pill btn-danger">Delete</a></td>*@
                                <td><a href="@Url.Action("Update")" class="btn btn--pill btn--green">Update</a></td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

Formulario/Views/Crud/Update.cshtml
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Update</h2>

Formulario/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Formulario/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Formulario/Views/Home/index.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Au Register Forms by Colorlib</title>
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">


    <!-- Main CSS-->
    <link href="~/Content/Template/css/main.css" rel="stylesheet" />
</head>

<body>
    <div class="page-wrapper bg-gra-01 p-t-180 p-b-100 font-poppins">
        <div class="wrapper wrapper--w780">
            <div class="card card-3">
                <div class="card-heading"></div>
                <div class="card-body">
                    <h2 class="title">Información</h2>
                    @using (Html.BeginForm())
                    {
                        <div class="input-group">
                            <input class="input--style-3" type="text" placeholder="Nombre" name="name">
                        </div>
                        <div class="input-group">
                            <input class="input--style-3 js-datepicker" type="text" placeholder="Apellido" name="lastName">
                            <i class="zmdi zmdi-calendar-note input-icon js-btn-calendar"></i>
                        </div>
                        <div class="input-group">
                            <input class="input--style-3 js-datepicker" type="email" placeholder="Correo" name="email">
                            <i class="zmdi zmdi-calendar-note input-icon js-btn-calendar"></i>
                        </div>
                        <div class="input-group">
                            <input class="input--style-3" type="text" placeholder="telefono" name="phone">
                        </div>
                        <div class="input-group">
                            <input class="input--style-3" type="text" placeholder="país" name="country">
                        </div>
                        <div class="p-t-10">
                            <button class="btn btn--pill btn--green" type="submit">Enviar</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>

    <!-- Jquery JS-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <!-- Vendor JS-->
    <script src="vendor/select2/select2.min.js"></script>
    <script src="vendor/datepicker/moment.min.js"></script>
    <script src="vendor/datepicker/daterangepicker.js"></script>

    <!-- Main JS-->
    <script src="js/global.js"></script>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>
<!-- end document-->

Formulario/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Title Page-->
    <title>CRUD</title>
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">


    <!-- Main CSS-->
    <link href="~/Content/Template/css/main.css" rel="stylesheet" />

    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CRUD", "Dashboard", "Crud", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Formulario</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>